### PR TITLE
Update readme

### LINKED ISSUE #14: SqlServerVersion not documented
Used but not shown in any links from readme: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.model.sqlserverversion

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #14

### CODE REVIEW

**Comment by jmezach** [comment]
Perhaps we should add the property to the sample code above as well?

**Comment by ErikEJ** [comment]
Done

**Comment by jmezach** [comment]
Great, thanks for the help.

**Comment by jmezach** [comment]
@ErikEJ Can you branch be deleted? I noticed that it is still lingering.

**Comment by ErikEJ** [comment]
Sure

**Pull request merged**
