### PR TITLE
Fix stream writing bug (different encoding with BOM)

### LINKED ISSUE #15: Bug in deployement script saving
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
     at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
     at System.IO.Compression.WrappedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
     at Microsoft.Data.Tools.Schema.Sql.Packaging.ZipWrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
     at MSBuild.Sdk.SqlProj.BuildDacpac.PackageBuilder.WritePart(FileInfo file, Package package, String path) in C:\Code\MSBuild.Sdk.SqlProj\src\BuildDacpac\PackageBuilder.cs:line 280
     at MSBuild.Sdk.SqlProj.BuildDacpac.PackageBuilder.AddPrePostScripts(FileInfo pre, FileInfo post, FileInfo outputFile) in C:\Code\MSBuild.Sdk.SqlProj\src\BuildDacpac\PackageBuilder.cs:line 76
     at MSBuild.Sdk.SqlProj.BuildDacpac.Program.BuildDacpac(PackageBuilderOptions options) in C:\Code\MSBuild.Sdk.SqlProj\src\BuildDacpac\Program.cs:line 89

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #15

### CODE REVIEW

**Comment by jmezach** [comment]
@ErikEJ Thanks for the quick fix. I'll merge this when the checks have completed so you'll get a new preview release.

**Comment by ErikEJ** [comment]
CI failed ??

**Comment by jmezach** [comment]
Yeah, not sure why. It looks like the SQL Server container was still trying to start, while the build was already trying to deploy the .dacpac. I've seen this a couple of times before, but it doesn't always happen. I'll have to figure out how I can wait for the container to fully be available before trying to deploy the package. I'll create a separate issue for that.

**Comment by jmezach** [comment]
@ErikEJ I've restarted CI and it succeeded on the second attempt. A new prerelease version of the package should be available soon.

**Pull request merged**
